---
# install Apache, MySql and PHP
- name: Update packages
  command: "apt-get update"

# Server version: Apache/2.4.29 (Ubuntu)
# PHP 7.2.17-0ubuntu0.18.04.1 (cli)
# Xdebug v2.6.0 copyright Derrick Rethans
# psql (PostgreSQL) 10.9
#
- name: install lamp stack
  apt:
    pkg:
      - apache2
      - php7.2
      - php7.2-zip
      - php7.2-apcu
      - php-xdebug
      - php-dom
      - postgresql
      - postgresql-contrib
      - postgis
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - php7.2-pgsql
    state: present
    update_cache: yes

- name: start apache service
  service:
    name: apache2
    state: started
    enabled: yes

- name: enable the php pdo_pgsql driver
  lineinfile:
    dest: /etc/php/7.2/apache2/php.ini
    regexp: ^.*?;extension=pdo_pgsql
    line: "extension=pdo_pgsql"

- name: enable the php pdo_pgsql driver
  lineinfile:
    dest: /etc/php/7.2/apache2/php.ini
    regexp: ^.*?;extension=pgsql
    line: "extension=pgsql"

# finished

