---
# install Apache, MySql and PHP
- name: Update packages
  command: "apt-get update"

# Server version: Apache/2.4.29 (Ubuntu)
# mysql  Ver 14.14 Distrib 5.7.26, for Linux (x86_64)
# PHP 7.2.17-0ubuntu0.18.04.1 (cli)
# Xdebug v2.6.0 copyright Derrick Rethans
# psql (PostgreSQL) 10.8
#
- name: install lamp stack
  apt:
    pkg:
      - apache2
      - mysql-server
      - php7.2
      - php7.2-mysql
      - php-xdebug
      - postgresql
      - postgresql-contrib
    state: present
    update_cache: yes

- name: start apache service
  service:
    name: apache2
    state: started
    enabled: yes

- name: start mysql service
  service:
    name: mysql
    state: started
    enabled: yes

# finished

