<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <title>Thank yoy</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">

    <h3>Thank you for registering with OSMAP</h3>
    <p>
        Your new key has been sent to your email address, it should arrive in approximatly 5 minutes.<br>
        This email address will also be used for OSMAP release notes or server maintenace messages.
    </p>

    <?php echo $this->fetch('termsofuse.phtml'); ?>

</div>

</body>
</html>