---
# This will test for python2, it will fail if not found
# upgrade manually, remove any other instances other than python 2.6!

- name: check for python 2
  command: "python -V"
  register: cmd_result
  failed_when: cmd_result.rc != 0
